version: '3.5'

volumes:
  postgres_volume:

services:
  category-service:
    restart: always
    build: .
    depends_on:
      - category_db
    ports:
      - "${GRPC_PORT:-5002}:${GRPC_PORT:-5002}"
      - "${HTTP_PORT:-8081}:${HTTP_PORT:-8081}"

  category_db:
    image: postgres:14-alpine3.17
    env_file:
      - .env
    ports:
      - "54322:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    env_file:
      - .env