version: '3.5'

volumes:
  postgres_volume:

services:
  product-service:
    restart: always
    build: .
    depends_on:
      - pg-local
    ports:
      - "${GRPC_PORT:-5001}:${GRPC_PORT:-5001}"
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"

  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - .env
    ports:
      - "${PG_PORT:-54321}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    env_file:
      - .env